### ISSUE TITLE
Server log‘s status usually "Disconnected"

### ISSUE THREAD

**Issue by chanssl** [Flexget/webui#20] opened 2018-02-11 12:59 UTC
System: Debian 8 64bit
Tasks can execute normally and update status. but server log's status usually display "Disconnected".

[![FlexGet Manager.png](https://i.loli.net/2018/02/11/5a803f565aca6.png)](https://i.loli.net/2018/02/11/5a803f565aca6.png)

**Comment by hot36952** [comment] 2018-07-03 07:04
I have encountered the same problem, how can I solve it?

**Comment by kristenmills** [comment] 2019-07-25 05:38
The screenshot you provided is from the old UI, I'm pretty sure that this issue should be fixed in the v2 of the UI but feel free to reopen if you notice it isn't.

**Closed by kristenmills** 2019-07-25 05:38 UTC
Labels: Angular UI

**Comment by DFP86** [comment] 2024-02-03 15:42
Version Info

Flexget: 3.11.14

Web UI: 2.0.29

API: 1.8.0
--------------------------------


The same problem...

![image](https://github.com/Flexget/webui/assets/12046701/999c2c41-04ae-4050-8728-e7d1b76241dd)

↑↑ The screenshot can found a lot of log are missing with time.

I think maybe the timezone not match with web-ui, so that in my timezone sometimes it will display 'Disconnected' in daytime.
At night the Server Log can be show...
I will update sometimes later.

Maybe the problem is in timezone？
Also I find the web-ui 'Tasks - Latest Executions' Start Time and End Time are display GMT timezone.
But I set the docker timezone with 'TZ=Asia/Shanghai'

Please check the reason~~Many Thanks~~~

**Comment by DFP86** [comment] 2024-02-03 15:44
> Version Info
> 
> Flexget: 3.11.14
> 
> Web UI: 2.0.29
> 
> ## API: 1.8.0
> The same problem...
> 
> ![image](https://private-user-images.githubusercontent.com/12046701/302045186-999c2c41-04ae-4050-8728-e7d1b76241dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NzUyMjUsIm5iZiI6MTcwNjk3NDkyNSwicGF0aCI6Ii8xMjA0NjcwMS8zMDIwNDUxODYtOTk5YzJjNDEtMDRhZS00MDUwLTg3MjgtZTdkMWI3NjI0MWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDE1NDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NDk1ZDZlZmI1ZTYzZTFkOTQ5ZGUyYmJmYWY3MGUxMWNjM2Y0ZTVkZDk0ZjFhYTg4OGY5YWJhZDRkYzAzZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dWhW2_XFpHX0uaY7mnX8lmcLFqhXpSi1cy4-TTqjLwE)
> 
> ↑↑ The screenshot can found a lot of log are missing with time.
> 
> I think maybe the timezone not match with web-ui, so that in my timezone sometimes it will display 'Disconnected' in daytime. At night the Server Log can be show... I will update sometimes later.
> 
> Maybe the problem is in timezone？ Also I find the web-ui 'Tasks - Latest Executions' Start Time and End Time are display GMT timezone. But I set the docker timezone with 'TZ=Asia/Shanghai'
> 
> Please check the reason~~Many Thanks~~~

Also I make sure the task run normally, Because the download is processing. Just web-ui display “Disconnected”.
